name: Luacheck
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: nebularg/actions-luacheck@v1
        with:
          args: '-r'
